- src/main/resources/static/css/main.css
- src/main/resources/static/css/schedule.css
- src/main/resources/templates/common/header.html
- src/main/resources/templates/schedule.html
> 250217 스케쥴 사이드바 수정

- src/main/java/com/hapla/comm/controller/CommController.java
- src/main/java/com/hapla/comm/model/mapper/CommMapper.java
- src/main/java/com/hapla/comm/model/service/CommService.java
- src/main/java/com/hapla/comm/model/vo/Comm.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/java/com/hapla/review/model/vo/PageInfo.java
- src/main/resources/mapper/comm-mapper.xml
- src/main/resources/static/css/reviewList.css
- src/main/resources/templates/comm/list.html
- src/main/resources/templates/comm/write.html
- src/main/resources/templates/review/list.html
- src/main/resources/templates/review/main.html
> 커뮤니티 작성 페이지, 리뷰 리스트 페이지 매핑

- src/main/java/com/hapla/comm/controller/CommController.java
- src/main/java/com/hapla/comm/model/service/CommService.java
- src/main/java/com/hapla/common/PageInfo.java
- src/main/java/com/hapla/common/Pagination.java
250223 PageInfo.java를 comm로 이동
> 250223 PageInfo.java를 comm로 이동

- src/main/java/com/hapla/comm/controller/CommController.java
- src/main/java/com/hapla/comm/model/mapper/CommMapper.java
- src/main/java/com/hapla/comm/model/service/CommService.java
- src/main/java/com/hapla/comm/model/vo/Reply.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/java/com/hapla/review/model/mapper/ReviewMapper.java
- src/main/java/com/hapla/review/model/service/ReviewService.java
- src/main/resources/mapper/comm-mapper.xml
- src/main/resources/mapper/review-mapper.xml
- src/main/resources/static/css/reviewList.css
- src/main/resources/templates/comm/detail.html
- src/main/resources/templates/comm/list.html
- src/main/resources/templates/comm/write.html
- src/main/resources/templates/review/list.html
> 250225 커뮤니티 상세보기 매핑 성공

- src/main/resources/static/css/search.css
- src/main/resources/templates/flightSearchResult.html
> 250225 항공권 css

- src/main/resources/static/css/search.css
- src/main/resources/templates/flightSearchResult.html
> 250225 항공권 조회 css 완성!

- src/main/resources/templates/common/header.html
> 250225 여행일정모달

- src/main/resources/templates/common/header.html
> 250225 여행일정모달 x 삭제

- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/vo/Trip.java
- src/main/resources/templates/schedule/scheduleCalendar.html
> 250226 스케쥴 일정 DB 저장 구현중

- src/main/java/com/hapla/review/controller/ReviewAjaxController.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/java/com/hapla/review/model/mapper/ReviewMapper.java
- src/main/java/com/hapla/review/model/service/ReviewService.java
- src/main/resources/mapper/review-mapper.xml
- src/main/resources/templates/review/list.html
- src/main/resources/templates/review/write.html
> 250228 리뷰 작성페이지 매핑

- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/css/header.css
- src/main/resources/static/css/scheduleList.css
- src/main/resources/static/js/schedule.js
- src/main/resources/static/js/scheduleList.js
- src/main/resources/static/js/trip.js
- src/main/resources/templates/common/header.html
- src/main/resources/templates/schedule/schedule.html
- src/main/resources/templates/schedule/scheduleList.html
> 250228 스케쥴 목록 DB 연동

- src/main/resources/static/css/schedule.css
- src/main/resources/static/js/schedule.js
- src/main/resources/templates/schedule/schedule.html
> 250302 스케쥴 사이드패널

- src/main/resources/static/css/header.css
> 250304 스케쥴 모달 css

- src/main/java/com/hapla/comm/controller/CommController.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/java/com/hapla/review/model/vo/Review.java
- src/main/resources/mapper/review-mapper.xml
- src/main/resources/static/css/list.css
- src/main/resources/static/css/reviewDetail.css
- src/main/resources/static/css/reviewList.css
- src/main/resources/static/css/reviewWrite.css
- src/main/resources/templates/review/detail.html
- src/main/resources/templates/review/list.html
- src/main/resources/templates/review/write.html
> 250304 찐 리뷰 상세보기 매핑

- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/css/header.css
- src/main/resources/static/js/scheduleDetail.js
- src/main/resources/templates/schedule/scheduleDetail.html
> 250304 여행 일정 모달 css 수정

- build.gradle
- src/main/java/com/hapla/common/controller/TestController.java
- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/java/com/hapla/schedule/model/vo/Detail.java
- src/main/java/com/hapla/users/controller/UsersController.java
- src/main/java/com/hapla/users/model/mapper/UsersMapper.java
- src/main/java/com/hapla/users/model/service/UsersService.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/mapper/users-mapper.xml
- src/main/resources/static/css/scheduleList.css
- src/main/resources/static/js/schedule.js
- src/main/resources/static/js/scheduleDetail.js
- src/main/resources/static/js/scheduleList.js
- src/main/resources/static/js/search.js
- src/main/resources/static/js/trip.js
- src/main/resources/templates/main.html
- src/main/resources/templates/place-detail.html
- src/main/resources/templates/schedule/scheduleCalendar.html
- src/main/resources/templates/schedule/scheduleDetail.html
- src/main/resources/templates/schedule/scheduleList.html
> 250305 되돌리기

- src/main/java/com/hapla/flights/controller/FlightController.java
- src/main/java/com/hapla/flights/model/vo/Airport.java
- src/main/resources/static/csv/airport.csv
- src/main/resources/static/csv/airports.csv
- src/main/resources/static/csv/airportsss.csv
- src/main/resources/static/js/flightSearchResult.js
- src/main/resources/static/js/search.js
- src/main/resources/templates/flightSearchResult.html
> 25/03/09 공항 검색 리스트 수정

- src/main/java/com/hapla/comm/model/mapper/CommMapper.java
- src/main/java/com/hapla/comm/model/service/CommService.java
- src/main/java/com/hapla/review/controller/ReviewAjaxController.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/resources/mapper/comm-mapper.xml
- src/main/resources/static/css/detail.css
- src/main/resources/templates/comm/detail.html
> 250309 커뮤니티 댓글 수정 삭제 작업중

- src/main/resources/static/js/trip.js
> 250310 스케쥴 모달 지역으로만 검색 가능

- src/main/java/com/hapla/comm/controller/CommController.java
- src/main/java/com/hapla/comm/model/mapper/CommMapper.java
- src/main/java/com/hapla/comm/model/service/CommService.java
- src/main/java/com/hapla/comm/model/vo/CLike.java
- src/main/java/com/hapla/review/controller/ReviewAjaxController.java
- src/main/resources/mapper/comm-mapper.xml
- src/main/resources/static/css/detail.css
- src/main/resources/templates/comm/detail.html
- src/main/resources/templates/comm/write.html
- src/main/resources/templates/review/write.html
> 250310 좋아요 기능 활성화

- src/main/resources/static/css/schedule.css
- src/main/resources/static/js/schedule.js
- src/main/resources/templates/schedule/schedule.html
> 250311 스케쥴 사이드패널 검색기능 구현중

- src/main/resources/static/css/schedule.css
- src/main/resources/static/js/schedule.js
- src/main/resources/templates/schedule/schedule.html
> 250312 스케쥴 사이드패널 장소 검색

- src/main/resources/static/js/schedule.js
> 250314 스케쥴 nearby 해결2

- src/main/resources/static/js/schedule.js
250314 스케쥴 타입 변경중(rank -> 인기순 변경)
> 250314 스케쥴 타입 변경중(rank -> 인기순 변경)

- src/main/java/com/hapla/schedule/model/vo/Detail.java
- src/main/resources/static/css/schedule.css
- src/main/resources/static/js/schedule.js
- src/main/resources/templates/schedule/schedule.html
> 250316 메모구현중

- src/main/java/com/hapla/comm/controller/CommController.java
- src/main/java/com/hapla/comm/model/mapper/CommMapper.java
- src/main/java/com/hapla/comm/model/service/CommService.java
- src/main/java/com/hapla/review/controller/ReviewAjaxController.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/java/com/hapla/review/model/mapper/ReviewMapper.java
- src/main/java/com/hapla/review/model/service/ReviewService.java
- src/main/resources/mapper/comm-mapper.xml
- src/main/resources/mapper/review-mapper.xml
- src/main/resources/static/css/detail.css
- src/main/resources/static/css/list.css
- src/main/resources/static/css/reviewList.css
- src/main/resources/templates/comm/detail.html
- src/main/resources/templates/comm/list.html
- src/main/resources/templates/review/detail.html
- src/main/resources/templates/review/list.html
> 250317 커뮤니티 및 리뷰 검색 성공

- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/java/com/hapla/schedule/model/vo/Detail.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/js/schedule.js
- src/main/resources/static/js/scheduleList.js
- src/main/resources/templates/schedule/list.html
- src/main/resources/templates/schedule/schedule.html
250317 스케쥴 db 저장O(메모,장소 변경해야됨)
> 250317 스케쥴 db 저장O(메모,장소 변경해야됨)

- src/main/resources/static/js/schedule.js
> 250318 스케쥴 detail 추가 정상화

- src/main/java/com/hapla/ajax/controller/AjaxController.java
- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/java/com/hapla/schedule/model/vo/Detail.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/js/schedule.js
- src/main/resources/static/js/scheduleCalendar.js
- src/main/resources/static/js/scheduleDetail.js
- src/main/resources/static/js/scheduleList.js
- src/main/resources/templates/schedule/detail.html
- src/main/resources/templates/schedule/schedule.html
> 250320 스케쥴 db 저장 구현중

- src/main/java/com/hapla/comm/controller/CommController.java
- src/main/java/com/hapla/comm/model/service/CommService.java
- src/main/java/com/hapla/review/controller/ReviewAjaxController.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/java/com/hapla/review/model/mapper/ReviewMapper.java
- src/main/java/com/hapla/review/model/service/ReviewService.java
- src/main/java/com/hapla/review/model/vo/RLike.java
- src/main/resources/mapper/review-mapper.xml
- src/main/resources/static/css/detail.css
- src/main/resources/static/css/reviewDetail.css
- src/main/resources/static/css/reviewList.css
- src/main/resources/templates/comm/detail.html
- src/main/resources/templates/comm/edit.html
- src/main/resources/templates/comm/list.html
- src/main/resources/templates/comm/write.html
- src/main/resources/templates/review/detail.html
- src/main/resources/templates/review/list.html
250321 커뮤니티 리뷰 좋아요 및 리뷰 삭제 기능 활성화
> 250321 커뮤니티 리뷰 좋아요 및 리뷰 삭제 기능 활성화

- src/main/java/com/hapla/ajax/controller/AjaxController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/js/schedule.js
250322 detail controller 수정중
ajaxController
detail에 아무것도 안들어감!
maps에는 들어감!
Detail 리스트 생성 for문이 문제 같음!
> 250322 detail controller 수정중

- src/main/java/com/hapla/review/controller/ReviewAjaxController.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/resources/mapper/comm-mapper.xml
- src/main/resources/static/css/detail.css
- src/main/resources/static/css/list.css
- src/main/resources/static/css/reviewDetail.css
- src/main/resources/static/css/reviewList.css
- src/main/resources/static/css/write.css
- src/main/resources/templates/comm/detail.html
- src/main/resources/templates/comm/edit.html
- src/main/resources/templates/comm/list.html
- src/main/resources/templates/review/detail.html
> 250322 커뮤니티 댓글 수정 삭제 활성화

- src/main/java/com/hapla/ajax/controller/AjaxController.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/java/com/hapla/schedule/model/vo/Detail.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/js/schedule.js
- src/main/resources/static/js/scheduleCalendar.js
- src/main/resources/static/js/trip.js
> 250322 스케쥴 detail db 저장 성공

- src/main/java/com/hapla/ajax/controller/AjaxController.java
- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/java/com/hapla/schedule/model/vo/Detail.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/css/scheduleDetail.css
- src/main/resources/static/js/scheduleDetail.js
- src/main/resources/static/js/scheduleEdit.js
- src/main/resources/templates/schedule/detail.html
- src/main/resources/templates/schedule/list.html
- src/main/resources/templates/schedule/scheduleEdit.html
> 250322 스케쥴 조회중

- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/css/scheduleEdit.css
- src/main/resources/static/js/scheduleDetail.js
- src/main/resources/templates/schedule/detail.html
- src/main/resources/templates/schedule/scheduleEdit.html
> 250322 스케쥴 조회/삭제 가능(수정 구현중)

- src/main/java/com/hapla/schedule/controller/ScheduleController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/java/com/hapla/schedule/model/vo/DetailMemo.java
- src/main/java/com/hapla/schedule/model/vo/DetailPlace.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/js/scheduleEdit.js
- src/main/resources/templates/schedule/scheduleEdit.html
> 250323 스케쥴 수정 구현중

- src/main/java/com/hapla/ajax/controller/AjaxController.java
- src/main/java/com/hapla/schedule/model/mapper/ScheduleMapper.java
- src/main/java/com/hapla/schedule/model/service/ScheduleService.java
- src/main/resources/mapper/schedule-mapper.xml
- src/main/resources/static/css/scheduleEdit.css
- src/main/resources/static/js/scheduleDetail.js
- src/main/resources/static/js/scheduleEdit.js
> 250323 수정 변경 성공

- src/main/java/com/hapla/review/controller/ReviewAjaxController.java
- src/main/resources/mapper/review-mapper.xml
- src/main/resources/templates/review/detail.html
> 250323 리뷰 에러 보완

- src/main/resources/static/js/scheduleEdit.js
> 250324 수정시 디테일로 페이지 이동

- src/main/resources/static/css/list.css
- src/main/resources/static/css/schedule.css
- src/main/resources/static/css/scheduleDetail.css
- src/main/resources/static/css/scheduleEdit.css
- src/main/resources/static/css/scheduleList.css
- src/main/resources/templates/schedule/detail.html
- src/main/resources/templates/schedule/list.html
- src/main/resources/templates/schedule/schedule.html
- src/main/resources/templates/schedule/scheduleEdit.html
> 250324 로고추가

- src/main/resources/static/js/schedule.js
> 250324 저장시 페이지 이동

- src/main/java/com/hapla/flights/controller/FlightController.java
> 250324 황성현 들여쓰기 잘해라-_-

- src/main/resources/static/css/schedule.css
- src/main/resources/static/css/scheduleEdit.css
- src/main/resources/templates/schedule/schedule.html
- src/main/resources/templates/schedule/scheduleEdit.html
> 250324 스케쥴 메모저장버튼

- src/main/java/com/hapla/comm/controller/CommController.java
- src/main/java/com/hapla/review/controller/ReviewAjaxController.java
- src/main/java/com/hapla/review/controller/ReviewController.java
- src/main/resources/mapper/comm-mapper.xml
- src/main/resources/mapper/review-mapper.xml
- src/main/resources/static/css/detail.css
- src/main/resources/templates/comm/detail.html
- src/main/resources/templates/comm/list.html
- src/main/resources/templates/review/detail.html
- src/main/resources/templates/review/list.html
> 250324 베타발표 컨펌 내용 수정

- src/main/resources/static/css/search.css
> no message

- src/main/resources/static/css/scheduleList.css
- src/main/resources/templates/schedule/detail.html
- src/main/resources/templates/schedule/list.html
- src/main/resources/templates/schedule/schedule.html
- src/main/resources/templates/schedule/scheduleEdit.html
> 250326 스케쥴 목록에 탑바 적용

- src/main/resources/static/css/schedule.css
- src/main/resources/static/css/scheduleEdit.css
- src/main/resources/templates/schedule/schedule.html
> 250326 스케쥴 css변경

- src/main/resources/templates/comm/edit.html
> 250327 닉네임 마지막 수정 !!

- src/main/resources/templates/comm/detail.html
> 250327 마지막 수정입니다 찐막
